// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RequestCapability, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.terminal.command-provider@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:66f8210cc8079012b8d8e6686e4853b5a4ed930e9a8275559691e4b63dd7a744";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const COMMAND_PROVIDER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const COMMAND_PROVIDER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const COMMAND_PROVIDER_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const COMMAND_PROVIDER_CONTRACT: CapabilityReference<CommandProviderClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_command_provider { () => { "{\"capability_id\":\"lenso.terminal.command-provider@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"catalog\",\"execute\"],\"operation_kinds\":{\"execute\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_command_provider_client {
    () => { "{\"capability_id\":\"lenso.terminal.command-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.terminal.command-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_command_provider_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.terminal.command-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_command_provider_client {
    () => { "{\"capability_id\":\"lenso.terminal.command-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.terminal.command-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const CATALOG_OPERATION: &str = "catalog";
pub const EXECUTE_OPERATION: &str = "execute";

pub use lenso_contract_runtime::{OptionalValue, RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogResponse {
    #[serde(rename = "commands")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub commands: Vec<CommandDefinition>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CommandDefinition {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "output_formats")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub output_formats: Vec<OutputFormat>,
    #[serde(rename = "parameters")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub parameters: Vec<CommandParameter>,
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: Vec<String>,
    #[serde(rename = "summary")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub summary: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum OutputFormat {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "json")]
    Json,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CommandParameter {
    #[serde(rename = "choices")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub choices: Vec<String>,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ParameterKind,
    #[serde(rename = "long")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub long: OptionalValue<String>,
    #[serde(rename = "multiple")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub multiple: bool,
    #[serde(rename = "required")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub required: bool,
    #[serde(rename = "short")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub short: OptionalValue<String>,
    #[serde(rename = "value_name")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub value_name: OptionalValue<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ParameterKind {
    #[serde(rename = "positional")]
    Positional,
    #[serde(rename = "option")]
    Option,
    #[serde(rename = "flag")]
    Flag,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CatalogError {
    CatalogInvalid,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteOpen {
    #[serde(rename = "arguments_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub arguments_json: RawJson,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "output_format")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub output_format: OutputFormat,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteMessage {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content: String,
    #[serde(rename = "content_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_type: ContentType,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: OutputKind,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ContentType {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "json")]
    Json,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum OutputKind {
    #[serde(rename = "stdout")]
    Stdout,
    #[serde(rename = "stderr")]
    Stderr,
    #[serde(rename = "progress")]
    Progress,
    #[serde(rename = "result")]
    Result,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecutionFailedPayload {
    #[serde(rename = "details_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub details_json: RawJson,
    #[serde(rename = "message")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message: String,
    #[serde(rename = "reason_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason_code: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExecuteError {
    ExecutionFailed { payload: ExecutionFailedPayload },
    InvalidArguments,
    NotFound,
    OutputLimitExceeded,
    PermissionDenied,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct CommandProviderCatalog;
impl RequestCapability for CommandProviderCatalog {
    type Request = CatalogRequest;
    type Response = CatalogResponse;
    type DomainError = CatalogError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CATALOG_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<CommandProviderRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).catalog(context, request)
    }
}

#[derive(Debug)]
pub struct CommandProviderExecute;
pub type CommandProviderExecuteEvent = StreamEvent<ExecuteMessage, ExecuteError>;
impl StreamCapability for CommandProviderExecute {
    type OpenRequest = ExecuteOpen;
    type Message = ExecuteMessage;
    type DomainError = ExecuteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for CatalogError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CatalogInvalid => serializer.serialize_str("catalog_invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CatalogError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "catalog_invalid" => Ok(Self::CatalogInvalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ExecuteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExecutionFailed { payload } => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("code", "execution_failed")?;
                map.serialize_entry("payload", payload)?;
                map.end()
            },
            Self::InvalidArguments => serializer.serialize_str("invalid_arguments"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OutputLimitExceeded => serializer.serialize_str("output_limit_exceeded"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExecuteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_arguments" => Ok(Self::InvalidArguments),
                "not_found" => Ok(Self::NotFound),
                "output_limit_exceeded" => Ok(Self::OutputLimitExceeded),
                "permission_denied" => Ok(Self::PermissionDenied),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                match code.as_str() {
                    "execution_failed" => {
                        let payload = object.remove("payload").ok_or_else(|| serde::de::Error::custom("structured Domain Error is missing a payload"))?;
                        let payload = serde_json::from_value(payload).map_err(serde::de::Error::custom)?;
                        Ok(Self::ExecutionFailed { payload })
                    },
                    _ => {
                        let payload = object.remove("payload");
                        let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                        Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
                    }
                }
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_catalog_request(value: &CatalogRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_request(wire: &str) -> Result<CatalogRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_catalog_response(value: &CatalogResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_response(wire: &str) -> Result<CatalogResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_catalog_error(value: &CatalogError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_error(wire: &str) -> Result<CatalogError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_execute_request(value: &ExecuteOpen) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_request(wire: &str) -> Result<ExecuteOpen, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_response(value: &ExecuteMessage) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_response(wire: &str) -> Result<ExecuteMessage, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_error(value: &ExecuteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_error(wire: &str) -> Result<ExecuteError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoCommandProviderCatalogResult {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure>;
}
impl __LensoIntoCommandProviderCatalogResult for Result<CatalogResponse, CatalogError> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoCommandProviderCatalogResult for Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> { self }
}
impl __LensoIntoCommandProviderCatalogResult for Result<CatalogResponse, lenso_plugin_authoring::PluginError<CatalogError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoCommandProviderCatalogResult for Result<CatalogResponse, CommandProviderCatalogInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(CommandProviderCatalogInvocationError::Domain(error)) => Ok(Err(error)),
            Err(CommandProviderCatalogInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoCommandProviderExecuteStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, CommandProviderExecuteInvocationError>;
}
impl<S> __LensoIntoCommandProviderExecuteStreamResult for Result<S, ExecuteError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, CommandProviderExecuteInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(CommandProviderExecuteInvocationError::Domain)
    }
}
impl<S> __LensoIntoCommandProviderExecuteStreamResult for Result<S, lenso_plugin_authoring::PluginError<ExecuteError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, CommandProviderExecuteInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(CommandProviderExecuteInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(CommandProviderExecuteInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoCommandProviderExecuteStreamResult for Result<S, CommandProviderExecuteInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, CommandProviderExecuteInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

pub trait CommandProviderProvider: fmt::Debug + 'static {
    fn catalog(&self, context: InvocationContext, request: CatalogRequest) -> NativeRequestFuture<CommandProviderCatalog>;
    fn execute(&self, context: InvocationContext, request: ExecuteOpen) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, CommandProviderExecuteInvocationError>>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_command_provider {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportCommandProvider;
        impl $crate::CommandProviderProvider for $plugin {
        fn catalog(&self, context: __LensoNativeSupportCommandProvider::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportCommandProvider::NativeRequestFuture<$crate::CommandProviderCatalog> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::catalog(&plugin, context, request).await;
                $crate::__LensoIntoCommandProviderCatalogResult::__lenso_into_result(result)
            })
        }
        fn execute(&self, context: __LensoNativeSupportCommandProvider::InvocationContext, request: $crate::ExecuteOpen) -> __LensoNativeSupportCommandProvider::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportCommandProvider::NativeStreamSession>, $crate::CommandProviderExecuteInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::execute(&plugin, context, request).await;
                $crate::__LensoIntoCommandProviderExecuteStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_command_provider {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportCommandProvider;
        impl $crate::CommandProviderProvider for $object {
        fn catalog(&self, context: __LensoNativeSupportCommandProvider::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportCommandProvider::NativeRequestFuture<$crate::CommandProviderCatalog> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::catalog(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoCommandProviderCatalogResult::__lenso_into_result(result)
            })
        }
        fn execute(&self, context: __LensoNativeSupportCommandProvider::InvocationContext, request: $crate::ExecuteOpen) -> __LensoNativeSupportCommandProvider::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportCommandProvider::NativeStreamSession>, $crate::CommandProviderExecuteInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::CommandProviderExecuteInvocationError::Runtime)?;
                let result = <$plugin>::execute(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoCommandProviderExecuteStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_command_provider {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportCommandProvider;
        impl $crate::CommandProviderProvider for $object {
        fn catalog(&self, context: __LensoNativeSupportCommandProvider::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportCommandProvider::NativeRequestFuture<$crate::CommandProviderCatalog> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::CommandProviderProvider>::catalog(plugin.as_ref(), context, request).await
            })
        }
        fn execute(&self, context: __LensoNativeSupportCommandProvider::InvocationContext, request: $crate::ExecuteOpen) -> __LensoNativeSupportCommandProvider::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportCommandProvider::NativeStreamSession>, $crate::CommandProviderExecuteInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::CommandProviderExecuteInvocationError::Runtime)?;
                <$plugin as $crate::CommandProviderProvider>::execute(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct CommandProviderRequestEndpoint { provider: Rc<dyn CommandProviderProvider> }

#[derive(Debug)]
pub struct CommandProviderEndpoint<P: CommandProviderProvider> { provider: Rc<P>, request_endpoint: CommandProviderRequestEndpoint }
impl<P: CommandProviderProvider> CommandProviderEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn CommandProviderProvider> = provider.clone();
        Self { provider, request_endpoint: CommandProviderRequestEndpoint { provider: request_provider } }
    }
}

impl<P: CommandProviderProvider> NativeRequestEndpoint for CommandProviderEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CATALOG_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CATALOG_OPERATION => {
                let Ok(request) = request.downcast::<CatalogRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).catalog(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

impl<P: CommandProviderProvider> NativeStreamEndpoint for CommandProviderEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        EXECUTE_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            EXECUTE_OPERATION => {
                let Ok(request) = request.downcast::<ExecuteOpen>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.execute(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(CommandProviderExecuteInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(CommandProviderExecuteInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_command_provider {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::CommandProviderEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_command_provider {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_command_provider!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct CommandProviderClient {
    catalog: NativeRequestHandle<CommandProviderCatalog>,
    execute: NativeStreamHandle<CommandProviderExecute>,
}
impl CommandProviderClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn catalog(&self, request: CatalogRequest) -> Result<CatalogResponse, CommandProviderCatalogInvocationError> {
        self.catalog.invoke(CATALOG_OPERATION, request).await
            .map_err(CommandProviderCatalogInvocationError::Runtime)?
            .map_err(CommandProviderCatalogInvocationError::Domain)
    }

    pub async fn catalog_with_context(&self, context: InvocationContext, request: CatalogRequest) -> Result<CatalogResponse, CommandProviderCatalogInvocationError> {
        self.catalog.invoke_with_context(CATALOG_OPERATION, context, request).await
            .map_err(CommandProviderCatalogInvocationError::Runtime)?
            .map_err(CommandProviderCatalogInvocationError::Domain)
    }

    pub async fn execute(&self, request: ExecuteOpen) -> Result<NativeStream<CommandProviderExecute>, CommandProviderExecuteInvocationError> {
        self.execute.open(EXECUTE_OPERATION, request).await
            .map_err(CommandProviderExecuteInvocationError::Runtime)?
            .map_err(CommandProviderExecuteInvocationError::Domain)
    }

    pub async fn execute_with_context(&self, context: InvocationContext, request: ExecuteOpen) -> Result<NativeStream<CommandProviderExecute>, CommandProviderExecuteInvocationError> {
        self.execute.open_with_context(EXECUTE_OPERATION, context, request).await
            .map_err(CommandProviderExecuteInvocationError::Runtime)?
            .map_err(CommandProviderExecuteInvocationError::Domain)
    }
}

impl CapabilityClient for CommandProviderClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            catalog: dependencies.one::<CommandProviderCatalog>()?,
            execute: dependencies.one_stream::<CommandProviderExecute>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for CommandProviderClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    catalog: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<CommandProviderCatalog>()?,
                    execute: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<CommandProviderExecute>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CommandProviderCatalogInvocationError {
    Domain(CatalogError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum CommandProviderExecuteInvocationError {
    Domain(ExecuteError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct CommandProviderGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> CommandProviderGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[CATALOG_OPERATION], &[EXECUTE_OPERATION])
            .map(|capability| Self { capability })
    }

    pub fn catalog(&self, request: &CatalogRequest) -> Result<CatalogResponse, lenso_guest_sdk::GuestError<CatalogError>> {
        self.capability.request(CATALOG_OPERATION, request)
    }

    pub fn execute(&self, request: &ExecuteOpen) -> Result<lenso_guest_sdk::GuestStream<H, ExecuteMessage, ExecuteError>, lenso_guest_sdk::GuestError<ExecuteError>> {
        self.capability.open_stream(EXECUTE_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct CommandProviderJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for CommandProviderJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[CATALOG_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[EXECUTE_OPERATION] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            CATALOG_OPERATION => {
                let value = request.downcast_ref::<CatalogRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            CATALOG_OPERATION => serde_json::from_value::<CatalogResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            CATALOG_OPERATION => serde_json::from_value::<CatalogError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            EXECUTE_OPERATION => {
                let value = request.downcast_ref::<ExecuteOpen>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_message(&self, operation: &str, message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            EXECUTE_OPERATION => {
                let value = message.downcast_ref::<ExecuteMessage>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_stream_message(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            EXECUTE_OPERATION => serde_json::from_value::<ExecuteMessage>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_stream_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            EXECUTE_OPERATION => serde_json::from_value::<ExecuteError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            CATALOG_OPERATION => {
                let request = serde_json::from_value::<CatalogRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<CommandProviderCatalog>()?;
                    match handle.invoke_with_context(CATALOG_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        match operation.as_str() {
            EXECUTE_OPERATION => {
                let request = serde_json::from_value::<ExecuteOpen>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<CommandProviderExecute>()?;
                    match handle.open_with_context(EXECUTE_OPERATION, context, request).await? {
                        Ok(stream) => Ok(Ok(lenso_runtime_codec::json_host_stream::<CommandProviderExecute>(
                            stream,
                            |value| serde_json::from_value::<ExecuteMessage>(value).map_err(|_| runtime_codec_protocol_failure()),
                            |message| serde_json::to_value(message).map_err(|_| runtime_codec_protocol_failure()),
                            |error| serde_json::to_value(error).map_err(|_| runtime_codec_protocol_failure()),
                        ))),
                        Err(error) => serde_json::to_value(error)
                            .map(Err)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
